function food_item(id,name,description,price){
    return {id, name, description}
}

let b0 = food_item(0, "Chedar cheese","Fresh chedar cheese made from cow milk. Unsweetened.", "$ 1.85");
let b1 = food_item(1, "Salted butter", "Fresh salted butter made from cow milk without added ingredients.", "$ 2.25");
let b2 = food_item(2, "Mix fruit jam", "Ingredients: Orange, Pineapple, Strawberry, Gelatin, Sugar, Salt.", "$ 1.20");
let b3 = food_item(3, "Pure bee honey", "100g in one jar.", "$ 3");
let b4 = food_item(4, "Banana", "Cavendish banans. Well ripen bananas from Sri Lanka", "$ 1");
let b5 = food_item(5, "Coconut milk", "Can enjoy with Flat bread, Steamed peas or beans.", "$ 1");
let b6 = food_item(6, "Coconut chutney", "Ingredients: Shreaded coconut, water, curd, coconut oil, fried spices.", "$ 3");
let b7 = food_item(7, "Coconut and spice paste", "Spice paste ingredients: Red chillie, onion, ginger, lemon juice, salt. Can enjoy with steamed peas and beans or with steamed sweet potatoes.", "$ 1.85");
let b8 = food_item(8, "Dhal curry", "Ingredients: Lentils, coconut milk, chillie, garlik, salt and other spices.", "$ 4");
let b9 = food_item(9, "Flat bread", "Ingredients: Wheat flour, coconut, salt, water.", "$ 1.85");
let b10 = food_item(10, "Steamed peas and beans mix", "Ingredients: Red beans, white beans, green peas, chickpeas. Can enjoy with coconut milk or with shreaded coconut and sour spice paste.", "$ 4");
let b11 = food_item(11, "Steamed white beans", "Can enjoy with coconut milk or with shreaded coconut and sour spice paste.", "$ 4" );
let b12 = food_item(12, "Fried mushrooms", "Fried mushrooms with added salt, pepper and garlic. Can enjoy with rice.", "$ 1.85" );
let b13 = food_item(13, "Steamed red beans", "Can enjoy with coconut milk or with shreaded coconut and sour spice paste.", "$ 4");
let b14 = food_item(14, "Bread", "Whole wheat bread. With more fibers and less calories", "$ 1");
let b15 = food_item(15, "Steamed sweet potatoes", "Can enjoy with shreaded coconut and sour spice paste.", "$ 1.25");
let b16 = food_item(16, "Steamed chickpeas", "Can enjoy with coconut milk or with shreaded coconut and sour spice paste.", "$ 4");
let b17 = food_item(17, "Rice", "Can enjoy with dhal curry.", "$ 1.85");

let list_breakfast_items = [];
list_breakfast_items.push(b0);
list_breakfast_items.push(b1);
list_breakfast_items.push(b2);
list_breakfast_items.push(b3);
list_breakfast_items.push(b4);
list_breakfast_items.push(b5);
list_breakfast_items.push(b6);
list_breakfast_items.push(b7);
list_breakfast_items.push(b8);
list_breakfast_items.push(b9);
list_breakfast_items.push(b10);
list_breakfast_items.push(b11);
list_breakfast_items.push(b12);
list_breakfast_items.push(b13);
list_breakfast_items.push(b14);
list_breakfast_items.push(b15);
list_breakfast_items.push(b16);
list_breakfast_items.push(b17);

let l0 = food_item(0, "Baked beans", "Ingredients: Green beans, butter, salt, pepper powder", "$ 1.85");
let l1 = food_item(1, "Corn soup", "Ingredients: Corn seeds, Corn flour, mushrooms, garlic, butter, salt, pepper powder", "$ 1.85");
let l2 = food_item(2, "Mixed veg noogles", "Ingredients: Wheat noobles, vegitables, sesami seeds, butter, salt, pepper powder", "$ 2.25");
let l3 = food_item(3, "Mixe veg rice", "Ingredients: Rice, vegitables, mushroom, green peas, corn seeds, raisins, cashews, mint, celery, basil, butter, salt", "$ 4.45");
let l4 = food_item(4, "Pasta and cheese", "Ingredients: Wheat pasta, Fresh milk, Cheese, fried mushroom, garlic, butter, pepper powder, salt", "$ 3.85");
let l5 = food_item(5, "Green pasta", "Ingredients: Wheat pasta, butter, almond milk, basil, mint, celery, rosemery, thyme, origano, salt, pepper powder", "$ 3.65");
let l6 = food_item(6, "Roasted veggies", "Includes: Cauliflower, Cabbage, Carrot, Okra, Squash, Celery, Potato, Corn, butter, salt, pepper powder", "$ 3.75");
let l7 = food_item(7, "Smashed potatoes", "Ingredients: Potato, fresh milk, butter, musted seeds, cumin seeds, basil, garlic, salt", "$ 3");
let l8 = food_item(8, "Veg burger", "Includes: Wheat bun, tomato, onion, celery leaves, cheese, fried mushroom, bell pepper, sesami seeds, salt, black pepper powder", "$ 2.95");
let l9 = food_item(9, "Rice", "Can enjoy with dhal curry.", "$ 1.85");
let l10 = food_item(10, "Dhal curry", "Ingredients: Lentils, coconut milk, chillie, garlik, salt and other spices.", "$ 4");
let l11 = food_item(11, "Bread", "Whole wheat bread.", "$ 1");

let list_lunch_items = [];
list_lunch_items.push(l0);
list_lunch_items.push(l1);
list_lunch_items.push(l2);
list_lunch_items.push(l3);
list_lunch_items.push(l4);
list_lunch_items.push(l5);
list_lunch_items.push(l6);
list_lunch_items.push(l7);
list_lunch_items.push(l8);
list_lunch_items.push(l9);
list_lunch_items.push(l10);
list_lunch_items.push(l11);

let d0 = food_item(0, "Idli", "Ingredients: Rice flour, Urdu dhal flour, Fenugreek powder, Salt, Water.", "$ 2.85");
let d1 = food_item(1, "Masala dosa", "Ingredients: Rice flour, Urdu dhal flour, Semolina, Water, Salt, Ghee, Potato, Cilantro, Cumin seeds, Musterd seeds, Garlic, Coconut chutney.", "$ 3");
let d2 = food_item(2, "Pasta salad", "Ingredients: Wheat pasta, Vegitables, Curd, Lemon juice, Salt, Black pepper.", "$ 3.25");
let d3 = food_item(3, "Dumpling soup", "Ingredients: Wheat flour, vegitables, mushroom, green peas, corn seeds, mint, celery, basil, butter, salt, water.", "$ 4");
let d4 = food_item(4, "Pizza", "Ingredients: Mozeralla Cheese, Cheddar cheese, fried mushroom, cauliflower, tomato, garlic, butter, italian seasonings, pepper powder, salt", "$ 4.85");
let d5 = food_item(5, "Upma", "Ingredients: Semolina, butter, coconut milk, basil, celery, garlic, musted seeds, salt, green pepper.", "$ 2.65");
let d6 = food_item(6, "Vegi soup", "Includes: Cauliflower, Cabbage, Carrot, Green onion, Squash, Celery, Potato, Corn, butter, salt, pepper powder", "$ 3.75");
let d7 = food_item(7, "Vegi salad", "Ingredients: Cabbage, Carrot, Cucumber, Bellpepper, Green peas, Onion, Basil, Mint, Curd, Lemon juice, Sugar, Green pepper, Black pepper.", "$ 3");
let d8 = food_item(8, "Salted butter", "Fresh salted butter made from cow milk without added ingredients.", "$ 2.25");
let d9 = food_item(9, "Rice", "Can enjoy with dhal curry.", "$ 1.85");
let d10 = food_item(10, "Dhal curry", "Ingredients: Lentils, coconut milk, chillie, garlik, salt and other spices.", "$ 4");
let d11 = food_item(11, "Bread", "Whole wheat bread. More fibers and less sugar", "$ 1");

let list_dinner_items = [];
list_dinner_items.push(d0);
list_dinner_items.push(d1);
list_dinner_items.push(d2);
list_dinner_items.push(d3);
list_dinner_items.push(d4);
list_dinner_items.push(d5);
list_dinner_items.push(d6);
list_dinner_items.push(d7);
list_dinner_items.push(d8);
list_dinner_items.push(d9);
list_dinner_items.push(d10);
list_dinner_items.push(d11);

let bev1 = food_item(0, "Banana milk shake", "Ingredients: Vanilla ice cream, fresh milk, banana, cinnamon powder, sugar, salt, white chocolate sprincles", "$ 2.65");
let bev2 = food_item(1, "Cappuchino", "Ingredients: Espresso, fresh cream, three sugar cubes", "$ 2.30");
let bev3 = food_item(2, "Carrot juice", "300ml in a glass", "$ 1.85");
let bev4 = food_item(3, "Chocolate milk shake", "Ingredients: Ice cream, fresh milk, chocolate syrup, cocoa powder, instant cofee powder, cinnamon, milk chocolate flakes, sugar, scrumbles, caramel sauce, salt", "$ 3.85");
let bev5 = food_item(4, "Espresso", "Aromatic espresso from fresh cofee beans with three sugar cubes", "$ 1.70");
let bev6 = food_item(5, "Green tea", "Green tea from fresh tea leaves", "$ 1.70");
let bev7 = food_item(6, "Lemon iced tea", "Iced tea with fresh lemon", "$ 1.85");
let bev8 = food_item(7, "Lemon juice", "300ml in a glass", "$ 1.85");
let bev9 = food_item(8, "Milk tea", "Ingredients: Tea, fresh milk, cardemom, ginger, cloves, basil, cinnamon, sugar, salt", "$ 2.75");
let bev10 = food_item(9, "Orange juice", "300ml in a glass", "$ 1.85");
let bev11 = food_item(10, "Orange smoothie", "Ingredients: Orange, fresh cream, ice cubes, sugar, salt, mint", "$ 2.50");
let bev12 = food_item(11, "Black tea", "Aromatic black tea from fresh black tea leaves to boost your day. Staples thee sugar cubes.", "$ 1.70");
let bev13 = food_item(12, "Strawberry smoothie", "Ingredients: Strawberries, fresh cream, ice cubes, sugar, salt, mint", "$ 2.85");
let bev14 = food_item(13, "Vanilla milk shake", "Ingredients: Fresh milk, vanilla ice cream, fresh vanilla from beans, white chocolate, honey comb, scrumbles, caramel sauce, sugar, salt, mint", "$ 3.20");

let list_beverages = [];
list_beverages.push(bev1);
list_beverages.push(bev2);
list_beverages.push(bev3);
list_beverages.push(bev4);
list_beverages.push(bev5);
list_beverages.push(bev6);
list_beverages.push(bev7);
list_beverages.push(bev8);
list_beverages.push(bev9);
list_beverages.push(bev10);
list_beverages.push(bev11);
list_beverages.push(bev12);
list_beverages.push(bev13);
list_beverages.push(bev14);

let dst1 = food_item(0, "Butterscotch ice cream", "Three scoops in one wafer bawl", "$ 1.70");
let dst2 = food_item(1, "Cherry cheese cake", "300g in one slice", "$ 3");
let dst3 = food_item(2,"Chocolate cake", "300g in one slice", "$ 2.85");
let dst4 = food_item(3, "Chocolate cheese cake", "300g in one slice", "$ 3");
let dst5 = food_item(4, "Chocolate ice cream", "Three scoops in one wafer bawl", "$ 1.70");
let dst6 = food_item(5, "Coconut pannacotta", "Coconut pannacotta with fresh fruit toping", "$ 2.85");
let dst7 = food_item(6, "Fruit salad", "Includes: Banana, Pineapple, Papaya, Watermelon, Apple, Mango, Grapes, Kiwi, Dragon fruit, Strawberry, Sugar, Salt", "$ 3");
let dst8 = food_item(7, "Lime cheese cake", "300g in one slice", "$ 3");
let dst9 = food_item(8, "Cheese cake", "300g in one slice", "$ 3");
let dst10 = food_item(9, "Red velvet cake", "300g in one slice", "$ 2.85");
let dst11 = food_item(10, "Strawberry cheese cake", "300g in one slice", "$ 3");
let dst12 = food_item(11, "Strawberry ice cream", "Three scoops in one wafer bawl", "$ 1.90");
let dst13 = food_item(12, "Tiramisu", "Ingredients: Eggs, sugar, heavy cream, mascarpone cheese, cofee, rum, cocoa powder, ladies fingers and dark chocolate", "$ 2.90");
let dst14 = food_item(13, "Vanilla ice cream", "Three scoops in one wafer bawl", "$ 1.50");

let list_desserts = [];
list_desserts.push(dst1);
list_desserts.push(dst2);
list_desserts.push(dst3);
list_desserts.push(dst4);
list_desserts.push(dst5);
list_desserts.push(dst6);
list_desserts.push(dst7);
list_desserts.push(dst8);
list_desserts.push(dst9);
list_desserts.push(dst10);
list_desserts.push(dst11);
list_desserts.push(dst12);
list_desserts.push(dst13);
list_desserts.push(dst14);

export {list_breakfast_items, list_lunch_items, list_dinner_items, list_beverages, list_desserts};